### ISSUE TITLE
2 Google Drive's app available?

### ISSUE THREAD

**Issue by jaroet** [tiddlydrive/tiddlydrive.github.io#13]
Thanks for reviving the TiddlyDrive development ... 

When I follow install instructions I see two apps in the "Add more apps" dialog on Google Drive. 
![image](https://user-images.githubusercontent.com/28713432/58752536-b65a6a00-84b0-11e9-8942-24306e2db1c1.png)

Which one is the correct one. You should mention this on the install page. 

Regards,
JeRoen

**Comment by LordRatte** [comment]
That's a good question, @jaroet. You have the correct one installed. The second one is a backup that was set up by @aneuhold who was helping me because I didn't have access to resources. He is planning on taking it down. 

@aneuhold, on this topic, I was thinking that perhaps you should just make it Private rather than removing it entirely. It would be good to have a spare one to use in the future.

**Comment by jaroet** [comment]
Good to know I installed the right one, thanks for confirming ...

**Comment by aneuhold** [comment]
Sorry about that. Tiddly Drive 2 is unpublished now. So it shouldn't be visible anymore. Thanks @jaroet!
