### ISSUE TITLE
Missing meta viewport settings in Mobile Chrome

### ISSUE THREAD

**Issue by mikegr** [tiddlydrive/tiddlydrive.github.io#5]
Hello, 
I'm using the JD Mobile Layout for viewing TiddlyWiki on mobile. 
http://j.d.simplemobile.tiddlyspot.com/

However on Chrome on Android It does not work.

I can see with the Chrome Developer Tools and Remote Debugging that the TiddlyDrive has this head 
```
<head>
    <title id="top-title">Mikes Wiki — a non-linear personal web notebook</title>
    <meta charset="utf-8">
    <link type="text/css" rel="stylesheet" href="index.css">
    <link rel="stylesheet" href="/materialize.min.css">
    <link rel="stylesheet" href="/icon.css">
    <script src="https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.I7X0AzVouI4.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCOE0nG8Zat0OwhsKEd_RMFwgVdQrA/cb=gapi.loaded_0" async=""></script><script src="/jquery.min.js"></script>
    <script src="/materialize.min.js"></script>
  </head>
```
and misses the usual 
```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

Of course it is included in the iframe later, but for some reason Mobile Chrome does not recognize that. In Desktop Chrome it works fine. Adding the meta tag with the debugger gives me the expected result. 

Not sure how to solve that properly. 
Thanks for your thoughts.

**Comment by LordRatte** [comment]
Hi, @mikegr.

Thanks for the thorough bug report. I have added the suggested change on the development repo (this one) and you can test it here. If your normal address looks like this:

`https://tiddlydrive.lordratte.info/?state=%7B%22ids%22:%5B%220BwsHdOe4HEkcRnIwSndwYVQ3LTQ%22%5D,%22action%22:%22open%22,%22userId%22:%22100462425070132368787%22%7D`

then you need to replace the domain part of the url with `https://tiddlydrive.github.io/` so that the url is `https://tiddlydrive.github.io/?state=%7B%22ids%22:%5B%220BwsHdOe4HEkcRnIwSndwYVQ3LTQ%22%5D,%22action%22:%22open%22,%22userId%22:%22100462425070132368787%22%7D`
`

You'll probably be asked to authorize again and then you can test the development features. Let me know if the changes work and then I'll deploy on the production server.

**Comment by mikegr** [comment]
Thank you very much. That works for me on Chrome for Android 63. 
Don't know about your solution I was just thinking what happens if you have a theme without mobile optimized theme and the meta tag would be set.

**Comment by LordRatte** [comment]
Would it be a problem, though? I don't have an example of a theme like that but I can't think it would do harm.

**Comment by mikegr** [comment]
I think with this meta tag zooming is disabled, because you say that the site is optimized for mobile. And if the site is not optimized , zooming is important for use on mobile. But I'm not an expert in mobile web.

**Comment by mikegr** [comment]
OK, I can still zoom, but it is rendered for a 300 to 400 virtual pixels screen depending on the device, which often is not covered by the site's theme. I'm good with the solution. I think without optimized theme for mobile, you wouldn't use it on mobile, anyway.

**Comment by LordRatte** [comment]
I can't say I'm much of an expert in mobile web either so I'll take your word for it. I agree that you wouldn't use un-optimized themes on mobile. I have been considering lifting everything out of the iframe which would probably prevent similar future problems but for now I'll leave it with this solution.

Anyway, I have deployed the change to production.

**Comment by mikegr** [comment]
Thanks
